all:
	g++ -g Q1-1_brute_force_knapsack.cpp -o Q1-1_brute_force_knapsack.out -std=c++11
	g++ -g Q1-2_greedy_algorithm.cpp -o Q1-2_greedy_algorithm.out -std=c++11
	g++ -g Q1-3_dynamic_programming_knapsack.cpp -o Q1-3_dynamic_programming_knapsack.out -std=c++11
	g++ -g Q2_dijkstra.cpp -o Q2_dijkstra.out -std=c++11
clean:
	rm -f Q1-1_brute_force_knapsack.out
	rm -f Q1-2_greedy_algorithm.out
	rm -f Q1-3_dynamic_programming_knapsack.out
	rm -f Q2_dijkstra.out